import {state, save, toggle, reset} from './storage.js';
import {mountQuiz} from './quiz.js';
import {mountLab} from './labs.js';
const main = document.querySelector('#main');
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function get(path, type='json') { const response = await fetch(path); if (!response.ok) throw new Error(`No s’ha pogut carregar ${path}`); return type === 'json' ? response.json() : response.text(); }
let course, activities, questions, routeVersion=0;
const rubric = ['Identifico les forces i les represento amb vectors.','Distingeixo les propietats mecàniques dels materials.','Classifico estructures i n’identifico els elements.','Explico els cinc esforços i el vinclament.','Diferencio resistència, rigidesa i estabilitat.','Justifico millores amb dades o observacions.'];
function progress() { const n = course.temes.filter(t => state.completed.includes(t.id)).length; document.querySelector('#progress-bar').style.width = `${n/course.temes.length*100}%`; document.querySelector('#progress-text').textContent = `${n} de ${course.temes.length} temes completats`; }
function header(label,title,description='') {return `<div class="page-head"><p class="eyebrow">${label}</p><h1>${title}</h1>${description?`<p>${description}</p>`:''}</div>`;}
function topicCards() {return `<div class="cards">${course.temes.map((t,i)=>`<a class="card" href="#tema/${t.id}"><div class="card-head"><span class="card-icon" aria-hidden="true">${t.icona}</span><span class="number">0${i+1}</span></div><h3>${esc(t.titol)}</h3><p>${esc(t.resum)}</p><div class="card-foot"><span class="${state.completed.includes(t.id)?'complete':''}">${state.completed.includes(t.id)?'✓ Completat':t.durada+' · Lectura + pràctica'}</span><strong aria-hidden="true">↗</strong></div></a>`).join('')}</div>`;}
function noteBlock(id,label='El meu esborrany') {return `<label class="note-label" for="note">${label}</label><textarea id="note" placeholder="Escriu què has observat, com ho expliques i quins dubtes tens…">${esc(state.notes[id]||'')}</textarea><span class="save-status" id="save-status" role="status">Es desa només en aquest navegador. Pots exportar-lo des del quadern.</span>`;}
function bindNote(id) { document.querySelector('#note').addEventListener('input', e=>{state.notes[id]=e.target.value;document.querySelector('#save-status').textContent=save()?'Desat en aquest navegador.':'No s’ha pogut desar. Exporta el quadern abans de sortir.';}); }
function home() {
  const next = course.temes.find(t=>!state.completed.includes(t.id)) || course.temes[0];
  main.innerHTML=`<section class="hero"><div class="hero-copy"><p class="eyebrow">Situació d’aprenentatge 01</p><h1>Forces que actuen.<br><em>Estructures<br>que aguanten.</em></h1><p>${esc(course.subtitol)} Observa el teu entorn i descobreix la tecnologia que el sosté.</p><a class="btn" href="#tema/${next.id}">${state.completed.length?'Continua aprenent':'Comença l’itinerari'} <span>→</span></a></div><img src="assets/bridge.svg" alt="Il·lustració d’un pont amb barres triangulades, pilars i una càrrega vertical"></section><div class="intro-strip"><div><span class="intro-icon">▤</span><div><b>${course.temes.length} temes per descobrir</b><small>Idees clares, pas a pas</small></div></div><div><span class="intro-icon">◇</span><div><b>Aprèn fent</b><small>Explora, prova i comprova</small></div></div><div><span class="intro-icon">✎</span><div><b>De la idea al prototip</b><small>Aplica-ho a un repte real</small></div></div></div><div class="section-heading"><div><h2>El teu itinerari</h2><p>Comença per les forces. Acaba mirant les estructures amb uns altres ulls.</p></div><a href="#aprendre">Veure els temes →</a></div>${topicCards()}<section class="lab-banner"><div><p class="eyebrow">LABORATORI OBERT</p><h3>I si hi afegeixes una diagonal?</h3><p>Canvia una variable, observa què passa i busca’n una explicació.</p></div><a class="btn secondary" href="#laboratori">Entra al laboratori ↗</a></section>`;
}
async function lesson(id,version) {
 const topic=course.temes.find(t=>t.id===id);if(!topic) return notFound();
 const html=await get(topic.fitxer,'text');if(version!==routeVersion)return;
 const i=course.temes.indexOf(topic), next=course.temes[i+1];
 main.innerHTML=`<a class="back" href="#aprendre">← Tots els temes</a>${header('TEMA '+String(i+1).padStart(2,'0')+' · '+topic.durada,esc(topic.titol))}<div class="reading-layout"><article class="article">${html}<h2>Comprova que ho entens</h2><div id="mini-quiz"></div><button class="btn secondary small" id="retry-topic">Torna a practicar</button>${noteBlock('tema:'+id,'Una idea que he après i un dubte')}<div class="lesson-bottom"><button class="btn" id="complete">${state.completed.includes(id)?'✓ Marcat com a completat':'Marca el tema com a completat'}</button><a class="text-link" href="${next?'#tema/'+next.id:'#repas'}">${next?'Tema següent':'Posa’t a prova'} →</a></div></article><aside class="lesson-side"><h2>En aquesta unitat</h2>${course.temes.map(t=>`<a class="${t.id===id?'current':''}" href="#tema/${t.id}">${esc(t.titol)}</a>`).join('')}<p>Entendre també és poder explicar-ho amb un exemple propi.</p></aside></div>`;
 mountQuiz(document.querySelector('#mini-quiz'),questions.filter(q=>q.tema===id),esc);
 bindNote('tema:'+id);
 document.querySelector('#complete').onclick=e=>{toggle('completed',id,!state.completed.includes(id));progress();e.target.textContent=state.completed.includes(id)?'✓ Marcat com a completat':'Marca el tema com a completat';};
 document.querySelector('#retry-topic').onclick=()=>{questions.filter(q=>q.tema===id).forEach(q=>delete state.answers[q.id]);save();route();};
}
function activityList() {main.innerHTML=header('OBSERVA · EXPERIMENTA · EXPLICA','Activitats amb propòsit','Prepara les teves evidències al quadern i presenta-les al lloc indicat pel professorat.')+`<div class="cards">${activities.map(a=>`<a href="#activitat/${a.id}" class="card"><div class="card-head"><span class="eyebrow">${a.codi}</span><span class="${state.done.includes(a.id)?'complete':''}">${state.done.includes(a.id)?'✓':'↗'}</span></div><h3>${esc(a.titol)}</h3><p>${esc(a.resum)}</p><div><span class="tag">${esc(a.dinamica)}</span></div><div class="card-foot"><span>${esc(a.entrega)}</span></div></a>`).join('')}</div>`;}
async function activity(id,version){
 const a=activities.find(a=>a.id===id);if(!a)return notFound();
 const html=await get(a.fitxer,'text');if(version!==routeVersion)return;
 main.innerHTML=`<a class="back" href="#activitats">← Totes les activitats</a>${header(a.codi,esc(a.titol))}<div class="activity-meta"><span class="tag">${esc(a.dinamica)}</span><span class="tag">Entrega: ${esc(a.entrega)}</span></div><article class="article">${html}<a href="#tema/${a.tema}" class="text-link">Repassa la teoria relacionada →</a>${noteBlock('activitat:'+id)}<label class="check-label"><input id="activity-done" type="checkbox" ${state.done.includes(id)?'checked':''}> He acabat aquesta activitat</label><p><small>Marcar-la com a feta no l’entrega al professorat.</small></p></article>`;
 bindNote('activitat:'+id);document.querySelector('#activity-done').onchange=e=>toggle('done',id,e.target.checked);
}
function laboratory(){
 main.innerHTML=header('EXPERIMENTA AMB UNA IDEA','El laboratori d’estructures','Abans de moure els controls, prediu què passarà. Després comprova-ho i explica per què.')+`<div class="lab-tabs" aria-label="Tria un experiment"><button data-lab="forces" aria-pressed="true">01 · Forces</button><button data-lab="triangulacio" aria-pressed="false">02 · Triangulació</button><button data-lab="estabilitat" aria-pressed="false">03 · Estabilitat</button></div><div id="lab"></div><div class="callout"><strong>Del model a la realitat</strong><p>Aquests models serveixen per explorar conceptes. Les estructures reals depenen també dels materials, de les unions i de totes les càrregues.</p></div>${noteBlock('laboratori','La meva predicció, observació i explicació')}`;
 let labNode=document.querySelector('#lab'); mountLab(labNode);bindNote('laboratori');
 document.querySelectorAll('[data-lab]').forEach(button=>button.onclick=()=>{document.querySelectorAll('[data-lab]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));const fresh=document.createElement('div');fresh.id='lab';labNode.replaceWith(fresh);labNode=fresh;mountLab(labNode,button.dataset.lab);});
}
function review(){
 main.innerHTML=header('PRACTICA SENSE PRESSA','Posa’t a prova','Respon abans de mirar l’explicació. Els errors indiquen què cal tornar a treballar; aquesta pràctica no és una nota oficial.')+`<div class="quiz-summary"><span id="quiz-score" aria-live="polite"></span><button class="btn secondary small" id="retry-all">Torna a començar</button></div><div id="quiz"></div>`;
 const score=()=>{const answered=questions.filter(q=>Number.isInteger(state.answers[q.id]));const correct=answered.filter(q=>state.answers[q.id]===q.correcta);document.querySelector('#quiz-score').textContent=`${answered.length}/${questions.length} respostes · ${correct.length} encerts`;};
 mountQuiz(document.querySelector('#quiz'),questions,esc,score);score();
 document.querySelector('#retry-all').onclick=()=>{questions.forEach(q=>delete state.answers[q.id]);save();review();};
}
function noteTitle(key) {if(key==='laboratori')return 'Laboratori';const [type,id]=key.split(':');return (type==='tema'?course.temes:activities).find(x=>x.id===id)?.titol || key;}
function download(){
 const entries=Object.entries(state.notes).filter(([,v])=>String(v).trim());
 const text=['EL MEU QUADERN · FORCES I ESTRUCTURES',`Exportat: ${new Date().toLocaleString('ca-ES')}`,'',...entries.flatMap(([k,v])=>[noteTitle(k),'-'.repeat(32),v,'']),'ACTIVITATS',...activities.map(a=>`${state.done.includes(a.id)?'[Fet]':'[Pendent]'} ${a.codi} · ${a.titol}`),'','AUTOAVALUACIÓ',...rubric.map((r,i)=>`${r} ${state.rubric[i]||'Sense valorar'}`)].join('\n');
 const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='quadern-forces-estructures.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
function notebook(){
 const notes=Object.entries(state.notes).filter(([,v])=>String(v).trim());
 main.innerHTML=header('PENSA SOBRE EL QUE APRENS','El meu quadern','Les teves idees, esborranys i descobertes. Es guarden en aquest navegador: exporta’ls per conservar-ne una còpia o portar-los a un altre dispositiu.')+`<div class="toolbar"><button class="btn" id="export">Descarrega el quadern ↓</button><button class="btn secondary" id="print">Imprimeix / Desa en PDF</button></div><h2>Els meus apunts</h2>${notes.length?notes.map(([key,value])=>`<section class="notebook-entry"><h2>${esc(noteTitle(key))}</h2><p>${esc(value)}</p><a class="text-link" href="#${key==='laboratori'?'laboratori':key.replace(':','/')}">Continua editant →</a></section>`).join(''):'<div class="empty">Encara no hi ha apunts. Escriu una reflexió en un tema, activitat o experiment i la trobaràs aquí.</div>'}<div class="section-heading"><h2>Seguiment d’activitats</h2></div><div class="table-wrap"><table><thead><tr><th>Activitat</th><th>Dinàmica</th><th>Entrega</th><th>Estat</th></tr></thead><tbody>${activities.map(a=>`<tr><td><a class="text-link" href="#activitat/${a.id}">${esc(a.titol)}</a></td><td>${esc(a.dinamica)}</td><td>${esc(a.entrega)}</td><td>${state.done.includes(a.id)?'✓ Feta':'Pendent'}</td></tr>`).join('')}</tbody></table></div><div class="section-heading"><h2>Autoavaluació</h2></div><div class="rubric">${rubric.map((r,i)=>`<label for="rubric-${i}">${r}<select id="rubric-${i}" data-rubric="${i}">${['Sense valorar','Necessito ajuda','Ho faig amb suport','Ho faig sol/a','Ho puc explicar'].map(v=>`<option ${state.rubric[i]===v?'selected':''}>${v}</option>`).join('')}</select></label>`).join('')}</div><p class="save-status" id="rubric-status" role="status"></p><details><summary>Gestiona les dades d’aquest navegador</summary><p>Si comparteixes ordinador, exporta el teu quadern abans d’esborrar les dades. Les dades esborrades no es poden recuperar des de la web.</p><button class="btn secondary" id="reset">Esborra el meu progrés i els apunts</button></details>`;
 document.querySelector('#export').onclick=download;document.querySelector('#print').onclick=()=>window.print();
 document.querySelectorAll('[data-rubric]').forEach(select=>select.onchange=()=>{state.rubric[select.dataset.rubric]=select.value;document.querySelector('#rubric-status').textContent=save()?'Autoavaluació desada.':'No s’ha pogut desar.';});
 document.querySelector('#reset').onclick=()=>{if(confirm('S’esborraran els apunts, les respostes i el progrés d’aquest navegador. Has exportat el quadern?')){reset();progress();notebook();}};
}
function notFound(){main.innerHTML=header('PÀGINA NO TROBADA','Aquest apartat no existeix.')+'<a class="btn" href="#inici">Torna a l’inici</a>';}
async function route(){
 const version=++routeVersion; const [page='inici',id]=location.hash.slice(1).split('/');
 const selected=page==='tema'?'aprendre':page==='activitat'?'activitats':page||'inici';
 document.querySelectorAll('[data-nav]').forEach(a=>{a.classList.toggle('active',a.dataset.nav===selected);if(a.dataset.nav===selected)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});
 document.title=`${selected==='inici'?'Forces i estructures':selected.charAt(0).toUpperCase()+selected.slice(1)} · Tecnologia 3r ESO`;
 main.innerHTML='<p role="status">Carregant…</p>';
 try {
 switch(page){case '':case 'inici':home();break;case 'aprendre':main.innerHTML=header('EXPLORA LES ESTRUCTURES','Aprèn, relaciona i comprova','Segueix l’ordre proposat o torna al tema que necessitis reforçar.')+topicCards();break;case 'tema':await lesson(id,version);break;case 'activitats':activityList();break;case 'activitat':await activity(id,version);break;case 'laboratori':laboratory();break;case 'repas':review();break;case 'quadern':notebook();break;default:notFound();}
 if(version===routeVersion){window.scrollTo(0,0);main.focus({preventScroll:true});}
 }catch(error){if(version===routeVersion)main.innerHTML=`<div class="error"><h1>No hem pogut obrir el contingut</h1><p>${esc(error.message)}</p><p>Comprova la connexió i torna-ho a provar.</p><button class="btn" onclick="location.reload()">Recarrega</button></div>`;}
}
try{[course,activities,questions]=await Promise.all([get('continguts/curs.json'),get('continguts/activitats.json'),get('continguts/preguntes.json')]);progress();window.addEventListener('hashchange',route);await route();}catch(error){main.innerHTML=`<div class="error"><h1>No s’ha pogut carregar la unitat</h1><p>${esc(error.message)}</p><p>Obre la web des de GitHub Pages o amb un servidor local, no fent doble clic a index.html.</p></div>`;}
