import {state,save,toggle} from './storage.js';
export const dossierLinks={propietats:['propietats'],esforcos:['esforcos'],triangulacio:['experiment-02'],paper:['final-02'],entorn:['final-03'],sintesi:['sintesi'],'aplica-tipus':['aplica-01'],'aplica-bicicleta':['aplica-03'],barres:['experiment-01'],organitza:['organitza'],romans:['lectura-romans'],leonardo:['lectura-leonardo'],'arc-biga':['experiencia-palleta','experiencia-arc','experiencia-biga'],'centre-gravetat':['teoria-08']};
const blocks=t=>[...(t.preguntes||[]),...(t.registres||[]),...(t.reflexions||[])];
function entries(t){return blocks(t).flatMap(f=>f.type==='table'?f.rows.flatMap((row,i)=>f.columns.map(c=>({key:`${f.id}.${i}.${c.id}`,label:`${f.label} / ${row} / ${c.label}`}))):[{key:f.id,label:f.label}]);}
function report(t,answers,blank=false){return [t.codi+' · '+t.titol,'',...entries(t).filter(f=>blank||String(answers[f.key]||'').trim()).flatMap(f=>[f.label,answers[f.key]||'(Pendent)',''])].join('\n');}
function downloadText(text,name){const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export async function dossierPage(id,{main,header,esc,get,current,index}){
 if(!id){
  const groups=[...new Set(index.map(t=>t.grup))];
  main.innerHTML=header('DEL DOSSIER A L’AULA','Tasques del dossier','Una pàgina per a cada activitat, experiment i experiència. Consulta l’enunciat, prepara el muntatge i recull les teves evidències.')+`<div class="dossier-intro"><strong>${index.length} tasques · ${index.filter(t=>state.done.includes('dossier:'+t.id)).length} marcades com a fetes</strong><p>Les respostes es desen només en aquest navegador i es poden exportar; no s’envien al professorat.</p></div><div class="dossier-filters"><label for="dossier-search">Cerca una tasca<input type="search" id="dossier-search" placeholder="Codi, títol o grup…"></label><label for="dossier-filter">Mostra<select id="dossier-filter"><option value="all">Totes les tasques</option><option value="pending">Pendents</option><option value="done">Fetes</option></select></label></div><p id="dossier-count" role="status"></p><div id="dossier-list"></div>`;
  const render=()=>{const query=main.querySelector('#dossier-search').value.toLocaleLowerCase('ca');const filter=main.querySelector('#dossier-filter').value;const filtered=index.filter(t=>(`${t.codi} ${t.titol} ${t.grup}`).toLocaleLowerCase('ca').includes(query)&&(filter==='all'||state.done.includes('dossier:'+t.id)===(filter==='done')));main.querySelector('#dossier-count').textContent=`${filtered.length} tasques`;main.querySelector('#dossier-list').innerHTML=groups.map(group=>{const items=filtered.filter(t=>t.grup===group);return items.length?`<section class="dossier-group"><h2>${esc(group)}</h2><div class="cards">${items.map(t=>`<a class="card dossier-card" href="#dossier/${t.id}"><span class="eyebrow">${esc(t.codi)}</span><h3>${esc(t.titol)}</h3><span class="${state.done.includes('dossier:'+t.id)?'complete':''}">${state.done.includes('dossier:'+t.id)?'✓ Feta':Object.values(state.dossier[t.id]?.answers||{}).some(v=>String(v).trim())?'En curs →':'Obre la tasca →'}</span></a>`).join('')}</div></section>`:'';}).join('')||'<p>No hi ha tasques amb aquests filtres.</p>';};
  main.querySelector('#dossier-search').oninput=render;main.querySelector('#dossier-filter').onchange=render;render();return;
 }
 const item=index.find(t=>t.id===id);if(!item){main.innerHTML=header('DOSSIER','Aquesta tasca no existeix.')+'<a href="#dossier">Torna a l’índex</a>';return;}
 const t=await get(item.fitxer);if(!current())return;
 const answers={...(state.dossier[id]?.answers||{})};
 function input(key,label,options){const value=answers[key]||'';return options?`<select id="d-${esc(key)}" data-dossier-field="${esc(key)}" aria-label="${esc(label)}"><option value="">Tria una resposta</option>${options.map(v=>`<option value="${esc(v)}" ${v===value?'selected':''}>${esc(v)}</option>`).join('')}</select>`:`<textarea id="d-${esc(key)}" data-dossier-field="${esc(key)}" aria-label="${esc(label)}" rows="3" placeholder="Escriu la teva resposta…">${esc(value)}</textarea>`;}
 function field(f){if(f.type==='table')return `<fieldset class="dossier-field"><legend>${esc(f.label)}</legend><div class="table-wrap dossier-table" role="region" aria-label="${esc(f.label)}" tabindex="0"><table><thead><tr><th scope="col">Element</th>${f.columns.map(c=>`<th scope="col">${esc(c.label)}</th>`).join('')}</tr></thead><tbody>${f.rows.map((r,i)=>`<tr><th scope="row">${esc(r)}</th>${f.columns.map(c=>`<td>${input(`${f.id}.${i}.${c.id}`,`${r} · ${c.label}`,c.options)}</td>`).join('')}</tr>`).join('')}</tbody></table></div></fieldset>`;return `<div class="dossier-field"><label for="d-${esc(f.id)}">${esc(f.label)}</label>${input(f.id,f.label)}</div>`;}
 const previous=index[index.indexOf(item)-1],next=index[index.indexOf(item)+1];
 main.innerHTML=`<a class="back" href="#dossier">← Totes les tasques del dossier</a>${header(esc(t.codi)+' · '+esc(t.grup),esc(t.titol))}<article class="article dossier-page" data-dossier-id="${id}"><div class="dossier-toolbar"><button class="btn secondary small" id="dossier-download">Descarrega aquesta tasca ↓</button><button class="btn secondary small" id="dossier-print">Imprimeix / Desa en PDF</button><a class="text-link" href="#quadern">El meu quadern →</a></div><p class="save-status" id="dossier-save" role="status">Es desa en aquest navegador. Per lliurar-ho, exporta les respostes i segueix les indicacions del professorat. Les fotos s’anoten com a enllaç o referència; no es pugen al web.</p>${t.aclariment?`<aside class="dossier-clarification"><h2>Abans de començar</h2><p>${esc(t.aclariment)}</p></aside>`:''}${t.lectura?`<section><h2>Lectura i context</h2>${t.lectura.map(s=>`<p>${esc(s)}</p>`).join('')}</section>`:''}${t.materials?`<section><h2>Materials</h2><ul>${t.materials.map(s=>`<li>${esc(s)}</li>`).join('')}</ul></section>`:''}${t.passos?`<section><h2>Què has de fer</h2><ol class="dossier-steps">${t.passos.map(s=>`<li>${esc(s)}</li>`).join('')}</ol></section>`:''}${(t.figures||[]).map(f=>`<figure class="dossier-figure"><a href="${esc(f.src)}" target="_blank" rel="noopener" aria-label="Amplia la figura: ${esc(f.alt)}"><img src="${esc(f.src)}" alt="${esc(f.alt)}"></a><figcaption>Prem la figura per ampliar-la.</figcaption></figure>`).join('')}<section class="dossier-original"><h2>La tasca i les teves respostes</h2>${t.banc?`<p class="dossier-bank"><strong>Banc de paraules:</strong> ${t.banc.map(esc).join(' · ')}</p>`:''}${t.preguntes.map(field).join('')}</section>${t.registres?.length?`<section class="dossier-extra"><h2>Registra les observacions</h2>${t.registres.map(field).join('')}</section>`:''}${t.reflexions?.length?`<section class="dossier-extra"><h2>Atura’t i reflexiona</h2>${t.reflexions.map(field).join('')}</section>`:''}${t.enllacos?.length?`<section><h2>Recursos relacionats</h2><ul>${t.enllacos.map(l=>`<li><a class="text-link" href="${esc(l.href)}">${esc(l.label)} →</a></li>`).join('')}</ul></section>`:''}<label class="check-label"><input type="checkbox" id="dossier-done" ${state.done.includes('dossier:'+id)?'checked':''}> He acabat i revisat aquesta tasca</label><p><small>És una marca personal de seguiment; no equival a lliurar-la ni a una qualificació.</small></p><nav class="lesson-bottom" aria-label="Ordre de les tasques">${previous?`<a href="#dossier/${previous.id}">← ${esc(previous.codi)}</a>`:'<span></span>'}${next?`<a href="#dossier/${next.id}">${esc(next.codi)} →</a>`:'<a href="#dossier">Torna a l’índex →</a>'}</nav></article>`;
 document.title=t.codi+' · '+t.titol+' · Tecnologia 3r ESO';
 const persist=()=>{state.dossier[id]={answers};const hasAnswers=Object.values(answers).some(v=>String(v).trim());state.notes['dossier:'+id]=hasAnswers?report(t,answers):'';main.querySelector('#dossier-save').textContent=save()?'Respostes desades en aquest navegador i disponibles al quadern.':'No s’ha pogut desar. Descarrega aquesta tasca abans de sortir.';};
 main.querySelectorAll('[data-dossier-field]').forEach(el=>el.addEventListener(el.tagName==='SELECT'?'change':'input',()=>{answers[el.dataset.dossierField]=el.value;persist();}));
 main.querySelector('#dossier-done').onchange=e=>{const ok=toggle('done','dossier:'+id,e.target.checked);main.querySelector('#dossier-save').textContent=ok?'Seguiment desat en aquest navegador.':'No s’ha pogut desar el seguiment.';};
 main.querySelector('#dossier-download').onclick=()=>downloadText(report(t,answers,true),'dossier-'+id+'.txt');
 main.querySelector('#dossier-print').onclick=()=>{
  const sheet=document.createElement('section');sheet.className='dossier-print-sheet';
  sheet.innerHTML=`<h1>${esc(t.codi+' · '+t.titol)}</h1>${t.aclariment?`<p>${esc(t.aclariment)}</p>`:''}${t.materials?`<h2>Materials</h2><p>${esc(t.materials.join(' · '))}</p>`:''}${t.lectura?`<h2>Lectura</h2>${t.lectura.map(s=>`<p>${esc(s)}</p>`).join('')}`:''}${t.passos?`<h2>Procediment</h2><ol>${t.passos.map(s=>`<li>${esc(s)}</li>`).join('')}</ol>`:''}${(t.figures||[]).map(f=>`<figure><img src="${esc(f.src)}" alt="${esc(f.alt)}"></figure>`).join('')}${t.banc?`<p>Banc de paraules: ${esc(t.banc.join(' · '))}</p>`:''}${[['Preguntes',t.preguntes],['Observacions',t.registres],['Reflexions',t.reflexions]].filter(([,fs])=>fs?.length).map(([title,fs])=>`<h2>${title}</h2><div class="dossier-print-answers">${esc(report({...t,preguntes:fs,registres:[],reflexions:[]},answers,true).split('\n').slice(2).join('\n'))}</div>`).join('')}`;
  main.append(sheet);document.body.classList.add('dossier-printing');
  const cleanup=()=>{sheet.remove();document.body.classList.remove('dossier-printing');};
  window.addEventListener('afterprint',cleanup,{once:true});window.print();
 };
}
