import {state,save,toggle} from './storage.js';
import {mountQuiz} from './quiz.js';
export function photoCard(photo,esc){return `<figure class="photo-card"><a href="${photo.font}" target="_blank" rel="noopener"><img src="${photo.src}" alt="${esc(photo.alt)}" loading="lazy" width="800" height="530" data-photo></a><figcaption><h3>${esc(photo.titol)}</h3><p>${esc(photo.pregunta)}</p><details><summary>Una pista per observar</summary><p>${esc(photo.pista)}</p></details><details><summary>Contrasta la teva explicació</summary><p>${esc(photo.explicacio)}</p></details><small>Foto: ${esc(photo.autor)} · <a href="${photo.urlLlicencia}">${esc(photo.llicencia)}</a> · <a href="${photo.font}">Original</a>. Sense modificacions del fitxer.</small></figcaption></figure>`;}
export async function expandedPage(page,id,{main,header,esc,get,current,noteBlock,bindNote}) {
 if(page==='sessions'||page==='sessio'){
  const sessions=await get('continguts/sessions.json');if(!current())return;
  if(page==='sessions'){
   main.innerHTML=header('DE LA PREGUNTA AL PROJECTE','El recorregut de les sessions','12 sessions orientatives de 55 minuts. El professorat pot adaptar el ritme i dedicar més temps a construir i provar.')+`<div class="session-list">${sessions.map(s=>`<a class="card session-card" href="#sessio/${s.id}"><span class="number">${String(s.numero).padStart(2,'0')}</span><div><h2>${esc(s.titol)}</h2><p>${esc(s.objectiu)}</p><span class="tag">${s.durada} min</span><span class="tag">${esc(s.dinamica)}</span>${state.done.includes('sessio:'+s.id)?'<span class="complete">✓ Treballada</span>':''}</div><span aria-hidden="true">→</span></a>`).join('')}</div>`;return;
  }
  const s=sessions.find(s=>s.id===id);if(!s){main.innerHTML=header('SESSIÓ NO TROBADA','Torna a la llista de sessions.')+'<a href="#sessions">Veure sessions</a>';return;}
  const html=await get(s.fitxer,'text');if(!current())return;
  const next=sessions[sessions.indexOf(s)+1];
  main.innerHTML=`<a class="back" href="#sessions">← Totes les sessions</a>`+header(`SESSIÓ ${s.numero} · ${s.durada} MIN`,esc(s.titol))+`<article class="article">${html}${noteBlock('sessio:'+id,'Què m’emporto d’aquesta sessió?')}<label class="check-label"><input id="session-done" type="checkbox" ${state.done.includes('sessio:'+id)?'checked':''}> He treballat aquesta sessió</label>${next?`<a class="btn" href="#sessio/${next.id}">Sessió següent →</a>`:'<a class="btn" href="#quadern">Obre el quadern →</a>'}</article>`;
  bindNote('sessio:'+id);main.querySelector('#session-done').onchange=e=>toggle('done','sessio:'+id,e.target.checked);return;
 }
 if(page==='previ'||page==='basics'){
  const basics=page==='basics';const [all,html]=await Promise.all([get('continguts/inici/preguntes.json'),basics?get('continguts/inici/basics.html','text'):Promise.resolve('')]);if(!current())return;
  const qs=all.filter(q=>q.id.startsWith(basics?'basics-':'previ-'));
  main.innerHTML=header(basics?'PREPARA LES EINES':'ABANS DE COMENÇAR',basics?'Conceptes bàsics de repàs':'Què sabem de les estructures?',basics?'Recupera el que necessitaràs per mesurar, representar i experimentar.':'No és un examen. Respon amb el que penses ara; «no ho sé» també és un punt de partida útil.')+`<article class="article">${basics?html:'<h2>1. Pensa abans de buscar</h2><p>Tria un pont, una cadira o una grua. Què el sosté? Quina peça creus que fallaria primer? Com ho podries comprovar?</p><div class="callout"><strong>Conserva la primera explicació</strong><p>Al final de la unitat tornaràs aquí per comparar les teves idees. Les primeres respostes del diagnòstic queden guardades en aquest navegador.</p></div>'}${noteBlock(basics?'basics':'previ',basics?'Un exemple amb unitats i un concepte que vull reforçar':'La meva explicació inicial, per què ho penso i dues preguntes')}<h2>${basics?'Comprova les eines':'2. Posa a prova les teves idees'}</h2><div id="entry-quiz"></div>${basics?'<button class="btn secondary" id="retry-basics">Practica una altra vegada</button>':'<h2>3. Contrasta amb el grup</h2><p>En quina pregunta heu discrepat? Expliqueu les raons abans de mirar el retorn. Anota un cas en què t’hagis replantejat la resposta.</p>'}<div class="entry-recommendation" id="entry-recommendation" aria-live="polite"></div><div class="lesson-bottom"><a class="btn" href="${basics?'#sessions':'#basics'}">${basics?'Comença les sessions':'Repassa els conceptes bàsics'} →</a></div></article>`;
  bindNote(basics?'basics':'previ');
  const recommend=()=>{const answered=qs.filter(q=>Number.isInteger(state.answers[q.id]));const errors=answered.filter(q=>state.answers[q.id]!==q.correcta);main.querySelector('#entry-recommendation').innerHTML=answered.length?`<p>Has respost ${answered.length} de ${qs.length} preguntes. ${errors.length?'Et pot ajudar revisar:':'Continua justificant les respostes amb exemples.'}</p>${[...new Set(errors.map(q=>q.tema))].map(t=>`<a class="tag" href="#tema/${t}">Revisa ${esc(t)}</a>`).join('')}`:'';};
  mountQuiz(main.querySelector('#entry-quiz'),qs,esc,recommend);recommend();
  if(basics)main.querySelector('#retry-basics').onclick=()=>{qs.forEach(q=>delete state.answers[q.id]);save();expandedPage(page,id,{main,header,esc,get,current,noteBlock,bindNote});};return;
 }
 if(page==='galeria'){
  const photos=await get('continguts/galeria.json');if(!current())return;
  main.innerHTML=header('OBSERVA · INTERPRETA · ARGUMENTA','Estructures amb nom propi','Mira primer les fotografies. Descriu allò que veus i separa-ho del que estàs deduint.')+`<div class="photo-gallery">${photos.map(p=>photoCard(p,esc)).join('')}</div><article class="article"><h2>Del món a l’aula</h2><p>Busca a l’entorn del centre una estructura amb una funció semblant. Fes-ne una fotografia pròpia o un croquis, identifica’n els elements i compara el camí de les càrregues.</p>${noteBlock('galeria','He observat… Interpreto que… Em falta saber…')}<a class="btn" href="#activitat/entorn">Analitza una estructura de l’entorn →</a></article>`;bindNote('galeria');
 }
}
