const defs = '<defs><pattern id="lab-grid" width="25" height="25" patternUnits="userSpaceOnUse"><path d="M25 0H0V25" stroke="#d6dacd" fill="none" stroke-width=".6"/></pattern><marker id="arrow" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0 0L6 3 0 6Z" fill="#ad490b"/></marker></defs><rect width="500" height="320" fill="url(#lab-grid)"/>';
const svg = body => `<svg viewBox="0 0 500 320" role="img" aria-label="Model visual interactiu">${defs}${body}</svg>`;
export function mountLab(root, kind = 'forces') {
  const labs = {
    forces: { title:'Dibuixa una força', controls:'<label for="force">Mòdul: <output id="force-value">60</output> N</label><input id="force" type="range" min="10" max="100" value="60" step="10"><label for="angle">Angle: <output id="angle-value">0</output>°</label><input id="angle" type="range" min="0" max="360" value="0" step="15"><p>L’angle es mesura des de l’horitzontal positiva, en sentit antihorari. Canviar-lo 180° inverteix el sentit.</p>', result:'La longitud indica el mòdul; l’orientació i la punta mostren la direcció i el sentit.' },
    triangulacio: {title:'Una diagonal ho canvia', controls:'<label for="push">Desplaçament imposat al marc sense diagonal: <output id="push-value">30</output></label><input id="push" type="range" min="-70" max="70" value="30"><label class="check-label"><input id="brace" type="checkbox"> Afegeix una diagonal</label><label for="brace-type">Tipus de diagonal</label><select id="brace-type"><option value="rigid">Barra rígida</option><option value="cable">Cable flexible tens inicialment</option></select><p>Model geomètric ideal amb barres de longitud fixa i unions articulades. La base està fixada. El control imposa moviment, no representa una força mesurada.</p>', result:''},
    estabilitat: {title:'On cau la vertical del pes?',controls:'<label for="base">Amplada de la base: <output id="base-value">140</output></label><input id="base" type="range" min="60" max="220" value="140" step="10"><label for="offset">Posició horitzontal del centre de gravetat: <output id="offset-value">0</output></label><input id="offset" type="range" min="-140" max="140" value="0" step="10"><label for="cg-height">Altura del centre de gravetat sobre la base: <output id="cg-height-value">100</output></label><input id="cg-height" type="range" min="40" max="150" step="10" value="100"><label for="tilt">Inclinació de la base: <output id="tilt-value">0</output>°</label><input id="tilt" type="range" min="0" max="45" step="1" value="0"><p>Cos rígid amb centre de gravetat prescrit, sota pes propi i sense lliscament ni ancoratges. La base s’inclina cap a la dreta. Unitats gràfiques; el contorn és esquemàtic i no implica massa uniforme.</p>',result:''}
  };
  const config = labs[kind];
  root.innerHTML = `<div class="lab-grid"><div class="lab-visual"></div><div class="lab-controls"><h2>${config.title}</h2>${config.controls}<div class="lab-result" aria-live="polite"></div></div></div>`;
  function draw() {
    const visual = root.querySelector('.lab-visual'), result = root.querySelector('.lab-result');
    root.querySelectorAll('input[type="range"]').forEach(input => { root.querySelector(`#${input.id}-value`).textContent = input.value; });
    if (kind === 'forces') {
      const force = +root.querySelector('#force').value, angle = +root.querySelector('#angle').value, rad = angle * Math.PI/180;
      const x = 250 + force*1.25*Math.cos(rad), y = 160-force*1.25*Math.sin(rad);
      visual.innerHTML = svg(`<path d="M50 160H450M250 25V295" stroke="#b2b8aa" stroke-dasharray="5 5"/><circle cx="250" cy="160" r="30" fill="#fff" stroke="#8f9985"/><path d="M250 160L${x} ${y}" stroke="#ad490b" stroke-width="4" marker-end="url(#arrow)"/><circle cx="250" cy="160" r="4" fill="#ad490b"/><text x="24" y="30" fill="#59624f" font-size="13">1 unitat gràfica = 0,8 N</text><text x="24" y="299" fill="#91400d" font-size="15">F = ${force} N · angle = ${angle}°</text>`);
      result.textContent = config.result;
    } else if (kind === 'triangulacio') {
      const braced=root.querySelector('#brace').checked,cable=root.querySelector('#brace-type').value==='cable',requested=+root.querySelector('#push').value,blocked=braced&&(!cable||requested>=0),shift=blocked?0:requested;
      const y = 245-Math.sqrt(150*150-shift*shift), x=145+shift;
      visual.innerHTML = svg(`<path d="M70 250H430" stroke="#87917d" stroke-width="3"/><path d="M145 245V95H345V245" fill="none" stroke="#bfc7b4" stroke-dasharray="5 5" stroke-width="3"/><path d="M145 245L${x} ${y}H${x+200}L345 245Z" fill="#e2e7d880" stroke="#727e66" stroke-width="7"/>${braced?`<path d="M145 245${cable&&!blocked?'Q250 205':'L'}${x+200} ${y}" stroke="#ad490b" stroke-width="${cable?3:6}" fill="none"/>`:''}<path d="M${x-65} ${y}H${x-15}" stroke="#ad490b" stroke-width="3" marker-end="url(#arrow)"/>${[[145,245],[x,y],[x+200,y],[345,245]].map(([cx,cy])=>`<circle cx="${cx}" cy="${cy}" r="7" fill="#fff" stroke="#68775b" stroke-width="3"/>`).join('')}<text x="40" y="300" fill="#59624f" font-size="13">${blocked?'La diagonal impedeix aquest moviment':braced?'Cable fluix: permet aquest moviment':'Sense diagonal: els angles poden canviar'}</text>`);
      result.innerHTML=braced&&cable&&!blocked?'<strong>El cable es destensa.</strong><p>Aquest moviment escurça la distància entre els seus extrems. Un cable flexible no pot empènyer com una barra comprimida.</p>':blocked?'<strong>La diagonal bloqueja el mecanisme.</strong><p>En una estructura real, les barres i les unions encara es poden deformar o fallar.</p>':'<strong>El marc canvia de forma.</strong><p>Les barres mantenen la longitud però les articulacions permeten variar els angles.</p>';
    } else {
      const base=+root.querySelector('#base').value,offset=+root.querySelector('#offset').value,height=+root.querySelector('#cg-height').value,tilt=+root.querySelector('#tilt').value,rad=tilt*Math.PI/180;
      const projection=offset+height*Math.tan(rad),outside=Math.abs(projection)>base/2+1e-8,boundary=Math.abs(Math.abs(projection)-base/2)<1e-8,cx=250+0.75*(offset*Math.cos(rad)+height*Math.sin(rad)),cy=210+0.75*(offset*Math.sin(rad)-height*Math.cos(rad));
      visual.innerHTML=svg(`<g transform="translate(250 210) rotate(${tilt}) scale(0.75)"><path d="M-180 0H180" stroke="#7f8975" stroke-width="3"/><path d="M${-base/2} 0H${base/2}" stroke="#6e8260" stroke-width="8"/><path d="M${-base/2} -5L${offset-20} ${-height-20}H${offset+20}L${base/2} -5Z" fill="#e0e5d6" stroke="#8a957e"/></g><circle cx="${cx}" cy="${cy}" r="7" fill="#ad490b"/><text x="${cx+10}" y="${cy-8}" font-size="13">CG</text><path d="M${cx} ${cy+8}V300" stroke="#ad490b" stroke-dasharray="5 5" stroke-width="2" marker-end="url(#arrow)"/><text x="15" y="25" font-size="13">Vertical del pes i base inclinada (${tilt}°)</text>`);
      result.classList.toggle('warn',outside||boundary);
      result.innerHTML=outside?'<strong>Tendeix a bolcar.</strong><p>La vertical del pes queda fora de la base de sustentació.</p>':boundary?'<strong>Al límit del bolcat.</strong><p>La vertical passa per la vora: una petita pertorbació pot fer-lo bolcar.</p>':'<strong>La vertical queda dins de la base.</strong><p>Hi ha marge abans d’arribar al límit de bolcat sota les condicions del model.</p>';
      result.innerHTML+=`<p>Intersecció amb la base: ${projection.toFixed(1)} unitats des del centre; límits ±${base/2}. ${Math.abs(offset)<base/2?'Llindar cap a la dreta: '+(Math.atan((base/2-offset)/height)*180/Math.PI).toFixed(1)+'°.':''} El dibuix mostra el criteri, no anima la caiguda.</p>`;
    }
  }
  root.addEventListener('input',draw); draw();
}
