import {state,save} from './storage.js';
export async function mountProject(root,esc){
 const brief=root.querySelector('#project-brief'),rubric=root.querySelector('#project-rubric');if(!brief||!rubric)return;
 const response=await fetch('continguts/projecte.json');if(!response.ok)throw Error('No s’ha pogut carregar el plec del projecte.');const config=await response.json();if(!brief.isConnected)return;const b=config.plec;
 brief.innerHTML=`<section class="learning-goals"><h2>Plec de treball</h2><ul><li>Llum lliure: <strong>${b.llumCm} cm</strong>.</li><li>Pressupost per versió: màxim ${b.fullsPerVersio} fulls A4 del mateix paper i ${b.cintaCmPerVersio} cm de cinta. Es pot reutilitzar material entre versions; registra el consum nou.</li><li>Càrrega total: increments de ${b.incrementG} g, fins a ${b.maximG} g com a màxim.</li><li>Aturada: fletxa de ${b.fletxaLimitMm} mm, dany, lliscament, inestabilitat o càrrega màxima, el que passi primer.</li></ul><p>És un protocol inicial de classe. El professorat l’ha de comprovar amb el paper i els suports disponibles i comunicar els ajustos abans de començar. Si no es poden obtenir exactament els increments, peseu i anoteu les masses reals.</p><p><strong>Criteri de treball:</strong> dues versions documentades i comparades. Arribar a la càrrega màxima no és una condició per aprovar.</p></section>`;
 state.practice['rubrica-projecte']??={};const saved=state.practice['rubrica-projecte'];
 rubric.innerHTML=`<h2>Rúbrica del projecte</h2><p>NA: encara no assolit · AS: assoliment satisfactori · AN: notable · AE: excel·lent. Autovalora cada criteri i cita una evidència. La selecció és orientativa; no calcula una nota oficial.</p>${config.criteris.map(c=>`<section class="rubric-criterion"><h3>${esc(c.titol)}</h3><dl>${config.nivells.map((n,i)=>`<dt>${n}</dt><dd>${esc(c.descriptors[i])}</dd>`).join('')}</dl><label for="level-${c.id}">El meu nivell en aquest criteri</label><select id="level-${c.id}" data-project-level="${c.id}"><option value="">Encara no valorat</option>${config.nivells.map(n=>`<option ${saved[c.id]?.level===n?'selected':''}>${n}</option>`).join('')}</select><label class="note-label" for="evidence-${c.id}">Quina evidència ho demostra?</label><textarea id="evidence-${c.id}" data-project-evidence="${c.id}" rows="2">${esc(saved[c.id]?.evidence||'')}</textarea></section>`).join('')}<p class="save-status" id="project-save" role="status"></p><a class="text-link" href="#quadern">Revisa i exporta la rúbrica al quadern →</a>`;
 function persist(){state.notes['rubrica-projecte']=['RÚBRICA DEL PROJECTE',...config.criteris.flatMap(c=>{const v=saved[c.id]||{};return [c.titol+': '+(v.level||'Sense valorar'),'Evidència: '+(v.evidence||''),''];})].join('\n');root.querySelector('#project-save').textContent=save()?'Rúbrica i evidències desades al quadern.':'No s’ha pogut desar. Exporta el quadern abans de sortir.';}
 rubric.querySelectorAll('[data-project-level]').forEach(s=>s.onchange=()=>{saved[s.dataset.projectLevel]??={};saved[s.dataset.projectLevel].level=s.value;persist();});rubric.querySelectorAll('[data-project-evidence]').forEach(t=>t.oninput=()=>{saved[t.dataset.projectEvidence]??={};saved[t.dataset.projectEvidence].evidence=t.value;persist();});
}
