import {graph} from './models.js';
export function mountChallenge(root,id){
 if(!['forces','suports'].includes(id))return;
 const box=document.createElement('section');box.className='experiment-question';
 const options=id==='forces'?'<option value="50,90">50 N vertical cap amunt</option><option value="80,180">80 N horitzontal cap a l’esquerra</option><option value="30,270">30 N vertical cap avall</option>':'<option value="60,25">Càrrega 60 N: esquerra 45 N i dreta 15 N</option><option value="60,75">Càrrega 60 N: esquerra 15 N i dreta 45 N</option><option value="40,50">Càrrega 40 N: 20 N a cada suport</option>';
 box.innerHTML=`<h2>Repte: troba la configuració</h2><label for="lab-target">Objectiu</label><select id="lab-target">${options}</select><p>Fes una predicció, ajusta els controls i comprova la proposta. Registra la prova si la vols conservar al quadern.</p><button class="btn" id="check-target">Comprova la configuració</button><p id="target-feedback" role="status"></p>`;
 root.append(box);const feedback=box.querySelector('#target-feedback');box.querySelector('#lab-target').onchange=()=>feedback.textContent='Nou objectiu: modifica els controls.';
 box.querySelector('#check-target').onclick=()=>{const [force,position]=box.querySelector('select').value.split(',').map(Number);const actualForce=+root.querySelector(id==='forces'?'#force':'#bridge-force').value,actualPosition=+root.querySelector(id==='forces'?'#angle':'#position').value;const correct=force===actualForce&&(id==='forces'?((actualPosition-position)%360===0):position===actualPosition);feedback.textContent=correct?'✓ Configuració correcta. Explica què has canviat i registra la prova.':id==='forces'?'Revisa el mòdul i el sentit: 0° és dreta, 90° amunt, 180° esquerra i 270° avall.':'Revisa la càrrega total i aproxima-la al suport que ha de rebre més força. La suma de reaccions ha de coincidir amb la càrrega.';};
}
export function springPlot(container,trials){
 const points=trials.filter(t=>t.numeric&&Number.isFinite(t.numeric.force)&&t.numeric.k>0);const old=trials.length-points.length;
 if(!points.length){container.innerHTML='<p>Registra proves noves per construir el gràfic força–allargament. Les proves anteriors continuen a la taula.</p>';return;}
 const maxF=Math.max(10,...points.map(p=>p.numeric.force)),maxX=Math.max(5,...points.map(p=>p.numeric.force/p.numeric.k));const colors=['#a64409','#17617c','#5d4588','#407044','#79510b'];const groups=[...new Set(points.map(p=>p.numeric.k))].sort((a,b)=>a-b);const x=v=>60+390*v/maxF,y=v=>260-210*v/maxX;
 container.innerHTML='<h3>Gràfic de les proves registrades</h3>'+graph(`<path d="M60 35V260H460" fill="none" stroke="#343a40" stroke-width="2"/><text x="185" y="308" font-size="14">Força F (N)</text><text x="15" y="24" font-size="13">Allargament x (cm)</text>${[0,.5,1].map(t=>`<text x="${x(t*maxF)}" y="282" text-anchor="middle" font-size="12">${(t*maxF).toFixed(1)}</text><text x="52" y="${y(t*maxX)+4}" text-anchor="end" font-size="12">${(t*maxX).toFixed(1)}</text>`).join('')}${points.map((p,i)=>`<circle cx="${x(p.numeric.force)}" cy="${y(p.numeric.force/p.numeric.k)}" r="5" fill="${colors[groups.indexOf(p.numeric.k)%colors.length]}"><title>Prova ${trials.indexOf(p)+1}: ${p.numeric.force} N; ${(p.numeric.force/p.numeric.k).toFixed(2)} cm; k=${p.numeric.k} N/cm</title></circle>`).join('')}`)+`<p>${groups.map((k,i)=>`<span style="color:${colors[i%colors.length]}">● k = ${k} N/cm</span>`).join(' · ')}</p><p>Gràfic de dades simulades. Compara punts amb la mateixa k; cada sèrie té pendent 1/k. Els punts coincidents se superposen. ${old?`${old} proves antigues sense dades numèriques es conserven a la taula i no es representen.`:''}</p>`;
}
