import {beamRatio,beamDeflection,beamMaterials,graph,range,scaffold,labels} from './models.js';
export function mount(root){
 scaffold(root,'La biga: amplada o alçada?','<label for="beam-material">Material de la biga</label><select id="beam-material" style="width:100%;max-width:100%;padding:8px">'+beamMaterials.map(m=>`<option value="${m.id}">${m.name} · E = ${m.modulus} GPa</option>`).join('')+'</select>'+range('load','Càrrega (N)',5,20,5,10)+range('span','Distància entre suports (cm)',50,150,10,100)+range('width','Amplada del perfil (mm)',5,20,5,10)+range('height','Alçada del perfil (mm)',5,20,5,10)+'<label class="check-label"><input id="constant-area" type="checkbox"> Mantén l’àrea de secció a 100 mm² (mateix volum si la longitud no canvia)</label>','Biga rectangular simplement recolzada i càrrega central. Tria el material: un mòdul elàstic E més alt significa menys deformació amb la mateixa càrrega i geometria. Els valors són orientatius; en la fusta depenen de l’espècie, la humitat i la direcció de la fibra. En el PMMA també influeixen la temperatura i el temps de càrrega. Sense pes propi. La fletxa δ és la distància vertical que baixa el centre respecte de la posició inicial: δ = F·L³/(48·E·I), amb I = b·h³/12 i unitats coherents. Aproximació elàstica de petites deformacions.');
 function draw(){
  labels(root);const force=+root.querySelector('#load').value,length=+root.querySelector('#span').value,inputWidth=+root.querySelector('#width').value,height=+root.querySelector('#height').value;
  const constant=root.querySelector('#constant-area').checked,width=constant?100/height:inputWidth;root.querySelector('#width').disabled=constant;root.querySelector('#width-value').textContent=Number(width.toFixed(2));
  const material=beamMaterials.find(m=>m.id===root.querySelector('#beam-material').value)||beamMaterials[0],modulus=material.modulus;
  const displacement=beamDeflection({force,length,width,height,modulus}),ratio=beamRatio({force,length,width,height,modulus}),delta=Math.min(100,ratio*12),left=250-length,right=250+length;
  root.querySelector('.lab-visual').innerHTML=graph(`<path d="M${left} 185H${right}" stroke="#adb7a0" stroke-dasharray="5 5"/><path d="M${left} 185Q250 ${185+2*delta} ${right} 185" stroke="#647455" stroke-width="8" fill="none"/><path d="M${left-12} 209L${left} 190 ${left+12} 209ZM${right-12} 209L${right} 190 ${right+12} 209Z" fill="#88947e"/><path d="M250 95V${177+delta}" stroke="#ad490b" stroke-width="3" marker-end="url(#model-arrow)"/><text x="266" y="120" font-size="14" fill="#91400d">${force} N</text><rect x="35" y="35" width="${width*3}" height="${height*3}" fill="#e7d9ba" stroke="#8e7c50"/><text x="30" y="115" font-size="12">Secció: ${Number(width.toFixed(2))} × ${height} mm</text><path d="M250 185H315M250 ${185+delta}H315M305 185V${185+delta}" stroke="#ad490b" stroke-width="1.5" fill="none"/><text x="320" y="${190+delta/2}" font-size="14" fill="#91400d">δ = ${displacement.toFixed(2)} mm</text><text x="30" y="303" font-size="12">Deformació exagerada i limitada al dibuix</text>`);
  root.querySelector('.lab-result').innerHTML=`<strong>Fletxa al centre: <output id="deflection-mm">${displacement.toFixed(2)}</output> mm</strong><p>El centre baixa ${displacement.toFixed(2)} mm respecte de la biga sense càrrega, segons el model: ${material.name}, E = ${modulus} GPa. El dibuix exagera i limita la deformació; el valor numèric es calcula independentment.</p><p>Deformació relativa: ${ratio.toFixed(2)} ×. Referència fixa d’acer (E = 200 GPa): 1.25 mm amb 10 N, 100 cm i secció de 10 × 10 mm.</p><p>Àrea de secció: ${(width*height).toFixed(0)} mm². ${constant?'Amplada calculada = 100/alçada; mantén també la llum per comparar amb igual volum.':'Canviar dimensions pot canviar la quantitat de material.'}</p>${displacement>length*10/100?'<p>La fletxa calculada supera l’1 % de la distància entre suports: és un avís orientatiu per revisar la hipòtesi de petites deformacions. No comprova la ruptura ni la seguretat de la biga.</p>':''}`;
 }
 root.addEventListener('input',draw);root.querySelector('#beam-material').addEventListener('change',draw);draw();
}
