import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,mkdir} from 'node:fs/promises';
import {extname,resolve,sep} from 'node:path';
const root=resolve('.');
const types={'.html':'text/html','.js':'text/javascript','.json':'application/json','.css':'text/css','.svg':'image/svg+xml'};
const server=createServer(async(req,res)=>{
 try{const pathname=new URL(req.url,'http://local').pathname;const file=resolve(root,'.'+decodeURIComponent(pathname.endsWith('/')?pathname+'index.html':pathname));if(!file.startsWith(root+sep))throw Error('Ruta');const body=await readFile(file);res.writeHead(200,{'Content-Type':types[extname(file)]||'application/octet-stream'});res.end(body);}catch{res.writeHead(404);res.end('Not found');}
});
await new Promise(r=>server.listen(0,'127.0.0.1',r));
const base=`http://127.0.0.1:${server.address().port}`;
let browser;
try{
 browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1440,height:1050}});const errors=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.url().startsWith(base)&&r.status()>=400)errors.push(r.url());});
 async function go(hash,selector){await page.goto(base+'/#'+hash);await page.locator(selector).first().waitFor();}
 await mkdir('test-output',{recursive:true});
 await go('inici','.hero');await page.screenshot({path:'test-output/inici.png',fullPage:true});
 await page.locator('.hero .btn').click();await page.locator('#entry-quiz').waitFor();
 await page.locator('#note').fill('Penso que una diagonal evita que canviïn els angles.');await page.locator('.answer').first().click();await page.reload();await page.locator('#entry-quiz').waitFor();assert.equal(await page.locator('#entry-quiz .question').count(),5);assert.match(await page.locator('#note').inputValue(),/diagonal/);assert.ok(await page.locator('.answer').first().isDisabled());
 await go('basics','#entry-quiz');assert.equal(await page.locator('#entry-quiz .question').count(),3);
 const sessions=JSON.parse(await readFile('continguts/sessions.json','utf8'));
 await go('sessions','.session-card');assert.equal(await page.locator('.session-card').count(),sessions.length);
 for(const s of sessions){await go('sessio/'+s.id,'#session-done');assert.ok((await page.locator('.session-steps li').count())>=4);}
 await page.locator('#session-done').check();await page.locator('#note').fill('Ara puc justificar la meva resposta.');
 for(const id of ['forces','triangulacio','estabilitat','flexio','molles','suports']){
  await go('laboratori/'+id,'#record-trial');await page.locator('#prediction').fill('La variable modificarà el resultat.');await page.locator('#record-trial').click();assert.equal(await page.locator('#trials tbody tr').count(),1);await page.locator('#conclusion').fill('Ho justifico amb la prova registrada.');await page.reload();await page.locator('#record-trial').waitFor();assert.equal(await page.locator('#trials tbody tr').count(),1);assert.match(await page.locator('#prediction').inputValue(),/variable/);
 }
 await go('laboratori/flexio','#height');await page.locator('#height').fill('20');assert.match(await page.locator('.lab-result').textContent(),/0.13/);await page.locator('#record-trial').click();assert.equal(await page.locator('#trials tbody tr').count(),2);await page.locator('#reset-controls').click();assert.equal(await page.locator('#height').inputValue(),'10');assert.equal(await page.locator('#trials tbody tr').count(),2);await page.screenshot({path:'test-output/laboratori.png',fullPage:true});
 await go('laboratori/suports','#position');await page.locator('#position').fill('0');assert.match(await page.locator('.lab-result').textContent(),/60.0 \+ 0.0/);
 await go('quadern','#export');assert.match(await page.locator('main').textContent(),/Ho justifico amb la prova/);const event=page.waitForEvent('download');await page.locator('#export').click();const download=await event;await download.saveAs('test-output/quadern.txt');assert.match(await readFile('test-output/quadern.txt','utf8'),/PROVES \(MODEL SIMULAT\)/);
 await go('repas','#quiz');assert.equal(await page.locator('#quiz .question').count(),JSON.parse(await readFile('continguts/preguntes.json','utf8')).length);await page.locator('#retry-all').click();await go('previ','#entry-quiz');assert.ok(await page.locator('.answer').first().isDisabled(),'El repàs no ha d’esborrar el diagnòstic');
 await go('galeria','.photo-card');assert.equal(await page.locator('.photo-card').count(),3);await page.locator('img[data-photo]').evaluateAll(async images=>{await Promise.all(images.map(async image=>{image.loading='eager';await image.decode();if(!image.naturalWidth)throw Error('Fotografia no carregada: '+image.src);}));});await page.screenshot({path:'test-output/galeria.png',fullPage:true});
 const course=JSON.parse(await readFile('continguts/curs.json','utf8'));
 for(const topic of course.temes){await go('tema/'+topic.id,'#complete');assert.ok(await page.locator('.idevice').count()>=4);await page.locator('.learning-figure img').evaluateAll(async images=>{await Promise.all(images.map(async im=>{im.loading='eager';await im.decode();}));});}
 await go('tema/forces','.check-task');await page.locator('[data-row="0"]').selectOption('Pes propi');await page.locator('.check-task').click();assert.match(await page.locator('.task-score').textContent(),/1 de 3/);await page.reload();await page.locator('.check-task').waitFor();assert.equal(await page.locator('[data-row="0"]').inputValue(),'Pes propi');await page.screenshot({path:'test-output/tema.png',fullPage:true});
 await go('glossari','#glossary-search');await page.locator('#glossary-search').fill('Vinclament');assert.equal(await page.locator('.glossary section').count(),1);
 // Verifica funcionalitats i persistència noves.
 await go('tema/esforcos','#reasoning-answer');await page.locator('#reasoning-answer').fill('Flexió amb deformació excessiva: afegeixo un suport intermedi.');await page.locator('[data-criterion="0"]').check();await page.reload();await page.locator('#reasoning-answer').waitFor();assert.match(await page.locator('#reasoning-answer').inputValue(),/suport intermedi/);assert.ok(await page.locator('[data-criterion="0"]').isChecked());
 await go('activitat/pont','#project-save');assert.equal(await page.locator('.rubric-criterion').count(),5);await page.locator('#level-projecte-1').selectOption('AN');await page.locator('#evidence-projecte-1').fill('Croquis amb el camí de càrregues.');await page.reload();await page.locator('#project-save').waitFor();assert.equal(await page.locator('#level-projecte-1').inputValue(),'AN');assert.match(await page.locator('#evidence-projecte-1').inputValue(),/Croquis/);await page.screenshot({path:'test-output/projecte.png',fullPage:true});
 await go('laboratori/forces','#check-target');await page.locator('#force').fill('50');await page.locator('#angle').fill('90');await page.locator('#check-target').click();assert.match(await page.locator('#target-feedback').textContent(),/correcta/);
 await go('laboratori/suports','#check-target');await page.locator('#position').fill('25');await page.locator('#check-target').click();assert.match(await page.locator('#target-feedback').textContent(),/correcta/);await page.locator('#position').fill('75');await page.locator('#check-target').click();assert.match(await page.locator('#target-feedback').textContent(),/Revisa/);
 await go('laboratori/triangulacio','#brace-type');await page.locator('#brace').check();await page.locator('#brace-type').selectOption('cable');await page.locator('#push').fill('-30');assert.match(await page.locator('.lab-result').textContent(),/destensa/);await page.locator('#push').fill('30');assert.match(await page.locator('.lab-result').textContent(),/bloqueja/);
 await go('laboratori/estabilitat','#tilt');await page.locator('#tilt').fill('30');assert.match(await page.locator('.lab-result').textContent(),/dins/);await page.locator('#cg-height').fill('150');assert.match(await page.locator('.lab-result').textContent(),/bolcar/);await page.screenshot({path:'test-output/estabilitat.png',fullPage:true});
 await go('laboratori/flexio','#constant-area');await page.locator('#constant-area').check();await page.locator('#height').fill('20');assert.ok(await page.locator('#width').isDisabled());assert.match(await page.locator('.lab-result').textContent(),/0.25/);assert.equal(await page.locator('#width-value').textContent(),'5');await page.locator('#record-trial').click();assert.match(await page.locator('#trials').textContent(),/100 mm²/);
 await go('laboratori/molles','#spring-plot');for(const v of ['2','4','6']){await page.locator('#spring-force').fill(v);await page.locator('#record-trial').click();}assert.ok(await page.locator('#spring-plot circle').count()>=3);await page.reload();await page.locator('#record-trial').waitFor();assert.ok(await page.locator('#spring-plot circle').count()>=3);await page.screenshot({path:'test-output/molles-grafic.png',fullPage:true});
 await go('quadern','#export');assert.match(await page.locator('main').textContent(),/Croquis amb el camí/);const exported=page.waitForEvent('download');await page.locator('#export').click();await (await exported).saveAs('test-output/quadern-ampliat.txt');assert.match(await readFile('test-output/quadern-ampliat.txt','utf8'),/Flexió amb deformació excessiva/);assert.match(await readFile('test-output/quadern-ampliat.txt','utf8'),/RÚBRICA DEL PROJECTE/);
 // Dades de la versió anterior: conserva apunts, progrés i proves sense números.
 const legacy=await browser.newPage();await legacy.goto(base);await legacy.evaluate(()=>localStorage.setItem('3tec-sa1-v1',JSON.stringify({completed:['forces'],done:['pont','sessio:prototip'],notes:{'tema:forces':'Apunts antics'},answers:{q1:1,'previ-1':1},rubric:{0:'Ho faig sol/a'},experiments:{molles:{prediction:'Predicció antiga',conclusion:'Conclusió antiga',trials:[{controls:'4 N; k=2',result:'2 cm'}]}}})));await legacy.goto(base+'/#laboratori/molles');await legacy.locator('#record-trial').waitFor();assert.equal(await legacy.locator('#trials tbody tr').count(),1);assert.equal(await legacy.locator('#prediction').inputValue(),'Predicció antiga');await legacy.locator('#record-trial').click();assert.equal(await legacy.locator('#trials tbody tr').count(),2);assert.equal(await legacy.locator('#spring-plot circle').count(),1);const restored=await legacy.evaluate(()=>JSON.parse(localStorage.getItem('3tec-sa1-v1')));assert.deepEqual(restored.completed,['forces']);assert.equal(restored.notes['tema:forces'],'Apunts antics');assert.equal(restored.answers['previ-1'],1);await legacy.close();
 for(const width of [390,768]){
  await page.setViewportSize({width,height:844});
  for(const [route,selector] of [['inici','.hero'],['sessions','.session-card'],['sessio/punt-partida','#note'],['basics','#entry-quiz'],['laboratori/flexio','#height'],['quadern','#export'],['galeria','.photo-card'],['tema/elements','#complete'],['tema/forces','.check-task'],['activitat/pont','#project-save'],['laboratori/molles','#spring-plot'],['laboratori/estabilitat','#tilt']]){await go(route,selector);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`Desbordament ${width}: ${route}`);}
  await go('inici','.hero');await page.screenshot({path:`test-output/inici-${width}.png`,fullPage:true});
 }
 assert.deepEqual(errors,[]);console.log('OK: sessions, diagnòstic preservat, models, registre persistent, exportació i disseny adaptable.');
}finally{await browser?.close();server.close();}
